import type { PlanLimits } from '../types/index.js';

export const PLAN_LIMITS: Record<string, PlanLimits> = {
  free: {
    maxUrls: 3,
    minInterval: '24h',
    historyDays: 7,
    maxWebhooks: 0,
    apiRateLimit: 10,
    features: {
      apiAccess: true,
      mcpAccess: true,
      discordIntegration: true,
      slackIntegration: false,
      webhookIntegration: false,
      schemaDiffDetail: false,
      perSourceSeverity: false,
      perSourceChannelRouting: false,
      digestMode: false,
    },
  },
  personal: {
    maxUrls: 10,
    minInterval: '1h',
    historyDays: 30,
    maxWebhooks: 3,
    apiRateLimit: 60,
    features: {
      apiAccess: true,
      mcpAccess: true,
      discordIntegration: true,
      slackIntegration: true,
      webhookIntegration: true,
      schemaDiffDetail: true,
      perSourceSeverity: true,
      perSourceChannelRouting: false,
      digestMode: true,
    },
  },
  team: {
    maxUrls: 50,
    minInterval: '15m',
    historyDays: 90,
    maxWebhooks: 10,
    apiRateLimit: 200,
    features: {
      apiAccess: true,
      mcpAccess: true,
      discordIntegration: true,
      slackIntegration: true,
      webhookIntegration: true,
      schemaDiffDetail: true,
      perSourceSeverity: true,
      perSourceChannelRouting: true,
      digestMode: true,
    },
  },
  business: {
    maxUrls: 200,
    minInterval: '5m',
    historyDays: 365,
    maxWebhooks: Infinity,
    apiRateLimit: 500,
    features: {
      apiAccess: true,
      mcpAccess: true,
      discordIntegration: true,
      slackIntegration: true,
      webhookIntegration: true,
      schemaDiffDetail: true,
      perSourceSeverity: true,
      perSourceChannelRouting: true,
      digestMode: true,
    },
  },
};
